"""Add RepeatActivity model

Revision ID: 166dec19116d
Revises: ec52d396e906
Create Date: 2025-07-04 06:59:21.796653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166dec19116d'
down_revision = 'ec52d396e906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repeat_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('intensity', sa.String(length=32), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('miles', sa.Float(), nullable=True),
    sa.Column('days_of_week', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repeat_activity')
    # ### end Alembic commands ###
