"""add total_weight to workout

Revision ID: fabfe471445c
Revises: cd360d7a13f9
Create Date: 2025-07-06 19:43:00.377804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabfe471445c'
down_revision = 'cd360d7a13f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('total_weight')

    # ### end Alembic commands ###
